--------------------------------------------------------
--  DDL for Trigger AU_CMS_CLAUSE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS_ADMIN"."AU_CMS_CLAUSE" 
AFTER UPDATE ON CMS_CLAUSE
FOR EACH ROW
BEGIN
  INSERT INTO CMS_CLAUSE_AUDIT(
  CLAUSE_ID,
  CLAUSE_NAME,
  CLAUSE_NUMBER,
  PARENT_ID,
  OWNER,
  CREATED_BY,
  CREATED_ON,
  CONTRACT_ID,
  MODIFIED_BY,
  MODIFIED_DATE) VALUES(
  CMS_ADMINISTRATION_PKG.L_MUT_CLAUSE_ID,
  CMS_ADMINISTRATION_PKG.L_MUT_CLAUSE_NAME,
  CMS_ADMINISTRATION_PKG.L_MUT_CLAUSE_NUMBER,
  CMS_ADMINISTRATION_PKG.L_MUT_PARENT_ID,
  CMS_ADMINISTRATION_PKG.L_MUT_OWNER,
  CMS_ADMINISTRATION_PKG.L_MUT_CREATED_BY,
  CMS_ADMINISTRATION_PKG.L_MUT_CREATED_ON,
  CMS_ADMINISTRATION_PKG.L_MUT_CONTRACT_ID,
  CMS_ADMINISTRATION_PKG.L_MUT_MODIFIED_BY,
  CMS_ADMINISTRATION_PKG.L_MUT_MODIFIED_DATE);

END;

/
ALTER TRIGGER "APPS_ADMIN"."AU_CMS_CLAUSE" ENABLE;
