--------------------------------------------------------
--  DDL for Trigger AU_CMS_REQUIREMENT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS_ADMIN"."AU_CMS_REQUIREMENT" 
AFTER UPDATE ON CMS_REQUIREMENT
FOR EACH ROW
BEGIN
 INSERT INTO CMS_REQUIREMENT_AUDIT(
    REQUIREMENT_ID,
    REQUIREMENT,
    NOTES,
    FREQUENCY_ID,
    UPLOAD_FILE_REQUIRED,
    START_DATE,
    CREATED_BY,
    CREATED_ON,
    IS_CM_NOTIFIED,
    NOTIFIED_DATE,
    CLAUSE_ID,
    MODIFIED_BY,
    MODIFIED_DATE,
    SCFLOWN_PROVISION
 ) VALUES(
    CMS_ADMINISTRATION_PKG.L_MUT_REQUIREMENT_ID,
    CMS_ADMINISTRATION_PKG.L_MUT_REQUIREMENT,
    CMS_ADMINISTRATION_PKG.L_MUT_NOTES,
    CMS_ADMINISTRATION_PKG.L_MUT_FREQUENCY_ID,
    CMS_ADMINISTRATION_PKG.L_MUT_UPLOAD_FILE_REQUIRED,
    CMS_ADMINISTRATION_PKG.L_MUT_START_DATE,
    CMS_ADMINISTRATION_PKG.L_MUT_REQ_CREATED_BY,
    CMS_ADMINISTRATION_PKG.L_MUT_REQ_CREATED_ON,
    CMS_ADMINISTRATION_PKG.L_MUT_IS_CM_NOTIFIED,
    CMS_ADMINISTRATION_PKG.L_MUT_NOTIFIED_DATE,
    CMS_ADMINISTRATION_PKG.L_MUT_REQ_CLAUSE_ID,
    CMS_ADMINISTRATION_PKG.L_MUT_REQ_MODIFIED_BY,
    CMS_ADMINISTRATION_PKG.L_MUT_REQ_MODIFIED_DATE,
    CMS_ADMINISTRATION_PKG.L_MUT_REQ_SCFLOWN_PROVISION
 );
END;

/
ALTER TRIGGER "APPS_ADMIN"."AU_CMS_REQUIREMENT" ENABLE;
