--------------------------------------------------------
--  DDL for Trigger AU_CMS_DELIVERABLE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS_ADMIN"."AU_CMS_DELIVERABLE" 
AFTER UPDATE ON CMS_DELIVERABLE
FOR EACH ROW
BEGIN
   INSERT INTO CMS_DELIVERABLE_AUDIT
   (DELIVERABLE_ID,SEQUENCE_NO,COMPOSITE_KEY,TYPE_ID, DUE_DATE,DIRECTORATE_ID,
      DEPARTMENT_ID,STATUS_ID,DATE_SUBMITTED,DATE_APPROVED,CREATED_BY,CREATED_ON,
      REQUIREMENT_ID,UPLOAD_FILE_REQUIRED,MODIFIED_BY,MODIFIED_DATE,DESCRIPTION,IS_INFORMATION_ONLY,NOTIFY_MANAGER,
      REASON_FOR_REJECTION, FREQUENCY_ID)
      VALUES (CMS_DELIVERABLE_PKG.L_MUT_DELIVERABLE_ID,CMS_DELIVERABLE_PKG.L_MUT_SEQUENCE_NO,CMS_DELIVERABLE_PKG.L_MUT_COMPOSITE_KEY,CMS_DELIVERABLE_PKG.L_MUT_TYPE_ID, CMS_DELIVERABLE_PKG.L_MUT_DUE_DATE,
      CMS_DELIVERABLE_PKG.L_MUT_DIRECTORATE_ID,
      CMS_DELIVERABLE_PKG.L_MUT_DEPARTMENT_ID,CMS_DELIVERABLE_PKG.L_MUT_STATUS_ID,CMS_DELIVERABLE_PKG.L_MUT_DATE_SUBMITTED,CMS_DELIVERABLE_PKG.L_MUT_DATE_APPROVED,CMS_DELIVERABLE_PKG.L_MUT_CREATED_BY,
      CMS_DELIVERABLE_PKG.L_MUT_CREATED_ON,
      CMS_DELIVERABLE_PKG.L_MUT_REQUIREMENT_ID,CMS_DELIVERABLE_PKG.L_MUT_UPLOAD_FILE_REQUIRED,CMS_DELIVERABLE_PKG.L_MUT_MODIFIED_BY,
      CMS_DELIVERABLE_PKG.L_MUT_MODIFIED_DATE,CMS_DELIVERABLE_PKG.L_MUT_DESCRIPTION,CMS_DELIVERABLE_PKG.L_MUT_IS_INFORMATION_ONLY,CMS_DELIVERABLE_PKG.L_MUT_NOTIFY_MANAGER,
      CMS_DELIVERABLE_PKG.L_MUT_REASON_FOR_REJECTION, CMS_DELIVERABLE_PKG.L_MUT_FREQUENCY_ID);

END;

/
ALTER TRIGGER "APPS_ADMIN"."AU_CMS_DELIVERABLE" ENABLE;
