--------------------------------------------------------
--  DDL for Trigger AU_CMS_CONTRACT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS_ADMIN"."AU_CMS_CONTRACT" 
AFTER UPDATE ON CMS_CONTRACT_OTHERTYPES
BEGIN
  INSERT INTO CMS_CONTRACT_OTHERTYPES_AUDIT(
  CONTRACT_ID,
  PARENT_ID,
  CONTRACT_NAME,
  CREATED_BY,
  CREATED_ON,
  MODIFIED_BY,
  MODIFIED_DATE,
  GROUP_ID,
  SHORT_NAME
  )
  VALUES
  (
    CMS_ADMINISTRATION_PKG.L_MUT_CNT_CONTRACT_ID,
    CMS_ADMINISTRATION_PKG.L_MUT_CNT_PARENT_ID,
    CMS_ADMINISTRATION_PKG.L_MUT_CONTRACT_NAME,
    CMS_ADMINISTRATION_PKG.L_MUT_CNT_CREATED_BY,
    CMS_ADMINISTRATION_PKG.L_MUT_CNT_CREATED_ON,
    CMS_ADMINISTRATION_PKG.L_MUT_CNT_MODIFIED_BY,
    CMS_ADMINISTRATION_PKG.L_MUT_CNT_MODIFIED_DATE,
    CMS_ADMINISTRATION_PKG.L_MUT_GROUP_ID,
    CMS_ADMINISTRATION_PKG.L_MUT_SHORT_NAME
   );

END;

/
ALTER TRIGGER "APPS_ADMIN"."AU_CMS_CONTRACT" ENABLE;
