--------------------------------------------------------
--  DDL for Trigger BI_CMS_ATTACHMENT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS_ADMIN"."BI_CMS_ATTACHMENT" 
BEFORE INSERT ON CMS_ATTACHMENT
FOR EACH ROW
BEGIN
  IF :NEW."ATTACHMENT_ID" IS NULL THEN
    SELECT "CMS_ATTACHMENT_ID_SEQ".NEXTVAL INTO :NEW."ATTACHMENT_ID" FROM DUAL;
  END IF;

  IF INSERTING AND :NEW.UPLOADED_BY IS NULL THEN
    :NEW.UPLOADED_BY := NVL(V('APP_USER'),USER);
    :NEW.UPLOADED_ON := SYSDATE;
  END IF;
END;

/
ALTER TRIGGER "APPS_ADMIN"."BI_CMS_ATTACHMENT" ENABLE;
