--------------------------------------------------------
--  DDL for Trigger BIU_CMS_CLAUSE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS_ADMIN"."BIU_CMS_CLAUSE" 
BEFORE INSERT OR UPDATE ON CMS_CLAUSE
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW."CLAUSE_ID" IS NULL THEN
    select "CMS_CLAUSE_ID_SEQ".nextval into :NEW."CLAUSE_ID" from dual;
  end if;
 if inserting and :new.created_by is null  then
        :new.created_by := NVL(V('APP_USER'),USER);
        :new.created_on := sysdate;
    end if;

    IF UPDATING AND :NEW.MODIFIED_BY IS NULL THEN
        :NEW.MODIFIED_BY := NVL(V('APP_USER'),USER);
        :new.MODIFIED_DATE := sysdate;
    END IF;

    IF UPDATING THEN
    CMS_ADMINISTRATION_PKG.L_MUT_CLAUSE_ID := :NEW.CLAUSE_ID;
    CMS_ADMINISTRATION_PKG.L_MUT_CLAUSE_NAME := :OLD.CLAUSE_NAME;
    CMS_ADMINISTRATION_PKG.L_MUT_CLAUSE_NUMBER := :OLD.CLAUSE_NUMBER;
    CMS_ADMINISTRATION_PKG.L_MUT_PARENT_ID := :OLD.PARENT_ID;
    CMS_ADMINISTRATION_PKG.L_MUT_OWNER := :OLD.OWNER;
    CMS_ADMINISTRATION_PKG.L_MUT_CREATED_BY := :OLD.CREATED_BY;
    CMS_ADMINISTRATION_PKG.L_MUT_CREATED_ON := :OLD.CREATED_ON;
    CMS_ADMINISTRATION_PKG.L_MUT_CONTRACT_ID := :OLD.CONTRACT_ID;
    CMS_ADMINISTRATION_PKG.L_MUT_MODIFIED_BY := :OLD.MODIFIED_BY;
    CMS_ADMINISTRATION_PKG.L_MUT_MODIFIED_DATE := :OLD.MODIFIED_DATE;

    IF (:NEW.MODIFIED_BY IS NULL) THEN
      :NEW.MODIFIED_DATE := SYSDATE;
    END IF;
    END IF;

END;

/
ALTER TRIGGER "APPS_ADMIN"."BIU_CMS_CLAUSE" ENABLE;
