--------------------------------------------------------
--  DDL for Trigger BIU_CMS_CONTRACT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS_ADMIN"."BIU_CMS_CONTRACT" 
BEFORE INSERT OR UPDATE ON CMS_CONTRACT_OTHERTYPES
FOR EACH ROW
BEGIN
   IF INSERTING AND :NEW."CONTRACT_ID" IS NULL THEN
    select "CMS_CONTRACT_ID_SEQ".nextval into :NEW."CONTRACT_ID" from dual;
  end if;
 if inserting and :new.created_by is null  then
        :new.created_by := NVL(V('APP_USER'),USER);
        :new.created_on := sysdate;
    end if;

    IF UPDATING AND :NEW.MODIFIED_BY IS NULL THEN
        :NEW.MODIFIED_BY := NVL(V('APP_USER'),USER);
        :new.MODIFIED_DATE := sysdate;
    END IF;

    IF UPDATING THEN
    CMS_ADMINISTRATION_PKG.L_MUT_CNT_CONTRACT_ID := :NEW.CONTRACT_ID;
    CMS_ADMINISTRATION_PKG.L_MUT_CNT_PARENT_ID := :OLD.PARENT_ID;
    CMS_ADMINISTRATION_PKG.L_MUT_CONTRACT_NAME := :OLD.CONTRACT_NAME;
    CMS_ADMINISTRATION_PKG.L_MUT_CNT_CREATED_BY := :OLD.CREATED_BY;
    CMS_ADMINISTRATION_PKG.L_MUT_CNT_CREATED_ON := :OLD.CREATED_ON;
    CMS_ADMINISTRATION_PKG.L_MUT_CNT_MODIFIED_BY := :OLD.MODIFIED_BY;
    CMS_ADMINISTRATION_PKG.L_MUT_CNT_MODIFIED_DATE := :OLD.MODIFIED_DATE;
    CMS_ADMINISTRATION_PKG.L_MUT_GROUP_ID := :OLD.GROUP_ID;
    CMS_ADMINISTRATION_PKG.L_MUT_SHORT_NAME := :OLD.SHORT_NAME;

    IF (:NEW.MODIFIED_BY IS NULL) THEN
      :NEW.MODIFIED_DATE := SYSDATE;
    END IF;
    END IF;
END;

/
ALTER TRIGGER "APPS_ADMIN"."BIU_CMS_CONTRACT" ENABLE;
