--------------------------------------------------------
--  DDL for Trigger BIU_CMS_DELIVERABLE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS_ADMIN"."BIU_CMS_DELIVERABLE" 
BEFORE INSERT OR UPDATE ON CMS_DELIVERABLE


FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW."DELIVERABLE_ID" IS NULL THEN
    select "CMS_DELIVERABLE_ID_SEQ".nextval into :NEW."DELIVERABLE_ID" from dual;
  end if;
 if inserting and :new.created_by is null  then
        :new.created_by := NVL(V('APP_USER'),USER);
        :new.created_on := sysdate;
    end if;

    IF UPDATING AND :NEW.MODIFIED_BY IS NULL THEN
        :NEW.MODIFIED_BY := NVL(V('APP_USER'),USER);
        :NEW.MODIFIED_DATE := SYSDATE;
    END IF;

    IF UPDATING THEN
     CMS_DELIVERABLE_PKG.L_MUT_DELIVERABLE_ID := :NEW.DELIVERABLE_ID;
     CMS_DELIVERABLE_PKG.L_MUT_SEQUENCE_NO := :OLD.SEQUENCE_NO;
     CMS_DELIVERABLE_PKG.L_MUT_COMPOSITE_KEY := :OLD.COMPOSITE_KEY;
     CMS_DELIVERABLE_PKG.L_MUT_TYPE_ID := :OLD.TYPE_ID;
     CMS_DELIVERABLE_PKG.L_MUT_DUE_DATE := :OLD.DUE_DATE;
     CMS_DELIVERABLE_PKG.L_MUT_DIRECTORATE_ID := :OLD.DIRECTORATE_ID;
     CMS_DELIVERABLE_PKG.L_MUT_DEPARTMENT_ID := :OLD.DEPARTMENT_ID;
     CMS_DELIVERABLE_PKG.L_MUT_STATUS_ID := :OLD.STATUS_ID;
     CMS_DELIVERABLE_PKG.L_MUT_DATE_SUBMITTED := :OLD.DATE_SUBMITTED;
     CMS_DELIVERABLE_PKG.L_MUT_DATE_APPROVED := :OLD.DATE_APPROVED;
     CMS_DELIVERABLE_PKG.L_MUT_CREATED_BY := :OLD.CREATED_BY;
     CMS_DELIVERABLE_PKG.L_MUT_CREATED_ON := :OLD.CREATED_ON;
     CMS_DELIVERABLE_PKG.L_MUT_REQUIREMENT_ID := :OLD.REQUIREMENT_ID;
     CMS_DELIVERABLE_PKG.L_MUT_UPLOAD_FILE_REQUIRED := :OLD.UPLOAD_FILE_REQUIRED;
     CMS_DELIVERABLE_PKG.L_MUT_MODIFIED_BY := :OLD.MODIFIED_BY;
     CMS_DELIVERABLE_PKG.L_MUT_MODIFIED_DATE := :OLD.MODIFIED_DATE;
     CMS_DELIVERABLE_PKG.L_MUT_DESCRIPTION := :OLD.DESCRIPTION;
     CMS_DELIVERABLE_PKG.L_MUT_IS_INFORMATION_ONLY := :OLD.IS_INFORMATION_ONLY;
     CMS_DELIVERABLE_PKG.L_MUT_NOTIFY_MANAGER := :OLD.NOTIFY_MANAGER;
     CMS_DELIVERABLE_PKG.L_MUT_REASON_FOR_REJECTION := :OLD.REASON_FOR_REJECTION;
     CMS_DELIVERABLE_PKG.L_MUT_FREQUENCY_ID := :OLD.FREQUENCY_ID;


      IF (:NEW.MODIFIED_BY IS NULL) THEN
        :NEW.MODIFIED_DATE := SYSDATE;
      END IF;

     IF :NEW.STATUS_ID =4 AND :NEW.STATUS_ID <> :OLD.STATUS_ID AND :NEW.IS_INFORMATION_ONLY = 'N' THEN
          :NEW.DATE_APPROVED := SYSDATE;
      ELSIF (:NEW.STATUS_ID = 3 OR :NEW.STATUS_ID = 4) AND :NEW.STATUS_ID <> :OLD.STATUS_ID THEN
          :NEW.DATE_SUBMITTED := SYSDATE;
      END IF;
    END IF;
END;

/
ALTER TRIGGER "APPS_ADMIN"."BIU_CMS_DELIVERABLE" ENABLE;
