--------------------------------------------------------
--  DDL for Procedure CMS_STATUS_CHANGE_PROC
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "APPS_ADMIN"."CMS_STATUS_CHANGE_PROC" AS
L_DELIVERABLE_ID NUMBER;
CURSOR C_DELIV IS
  SELECT DELIVERABLE_ID FROM VW_CMS_DELIVERABLE_DETAILS WHERE
    STATUS_ID =3 AND TRUNC(DATE_SUBMITTED) - TRUNC(SYSDATE) <= -60;
BEGIN
  OPEN C_DELIV;
  LOOP
    FETCH C_DELIV INTO L_DELIVERABLE_ID; EXIT WHEN C_DELIV %NOTFOUND;
    IF L_DELIVERABLE_ID IS NOT NULL THEN
      UPDATE CMS_DELIVERABLE SET STATUS_ID=6,DATE_APPROVED=SYSDATE WHERE
        DELIVERABLE_ID=L_DELIVERABLE_ID;
    END IF;
  END LOOP;
  CLOSE C_DELIV;
END CMS_STATUS_CHANGE_PROC;

/
