--------------------------------------------------------
--  DDL for Package Body CMS_LOOKUP_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS_ADMIN"."CMS_LOOKUP_PKG" AS

  PROCEDURE GetDeliverableLookupValues (
                            TYPECUR OUT DeliverableCur,
                            DIRECTORATECUR OUT DELIVERABLECUR,
                            NOTIFICATIONCUR OUT DELIVERABLECUR,
                            SSORECEIPIENTSCUR OUT DELIVERABLECUR
                             ) AS
LOCALTYPECUR DELIVERABLECUR;
LOCALDRTCUR DELIVERABLECUR;
LOCALNOTIFYSCHED DELIVERABLECUR;
LOCALSSORECEIPIENTS DELIVERABLECUR;

  BEGIN
    OPEN LOCALTYPECUR FOR
        SELECT DUMMY_ID AS CONTRACT_ID,DUMMY_DESC AS CONTRACT_NAME FROM CMS_DUMMY_LOOKUP UNION
        SELECT CONTRACT_ID,CONTRACT_NAME FROM CMS_CONTRACT_OTHERTYPES  WHERE IS_ACTIVE='Y' AND GROUP_ID IN (2,3);

    OPEN LOCALDRTCUR FOR
      SELECT ORG_ID,DESCRIPTION FROM SID.ORGANIZATIONS WHERE ORG_LEVEL = 2 AND STATUS='A' ORDER BY DESCRIPTION;

     OPEN LOCALNOTIFYSCHED FOR
      SELECT LOOKUP_ID, LOOKUP_DESC FROM CMS_LOOKUP WHERE IS_ACTIVE='Y' AND LOOKUP_GROUP = 'Notification' ORDER BY LOOKUP_ID ;

    OPEN LOCALSSORECEIPIENTS FOR
      SELECT MGR.MANAGER_ID, PC.EMPLOYEE_NAME FROM CMS_MANAGER MGR, DW_PEOPLE_CURRENT PC WHERE MGR.IS_ACTIVE='Y' AND MGR.MANAGER_TYPE='SSO' AND MGR.SLAC_ID = PC.EMPLOYEE_ID
        ORDER BY PC.EMPLOYEE_NAME;


    TYPECUR := LOCALTYPECUR;
    DIRECTORATECUR:=LOCALDRTCUR;
    NOTIFICATIONCUR:=LOCALNOTIFYSCHED;
    SSORECEIPIENTSCUR:=LOCALSSORECEIPIENTS;


  END GetDeliverableLookupValues;

END CMS_LOOKUP_PKG;

/
