--------------------------------------------------------
--  DDL for Package Body CMS_FILE_UPLOAD_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "APPS_ADMIN"."CMS_FILE_UPLOAD_PKG" AS

  PROCEDURE PROC_INS_FILEDATA
  (
      PI_DELIVERABLE_ID IN CMS_ATTACHMENT.DELIVERABLE_ID%TYPE,
      PI_FILE_NAME IN CMS_ATTACHMENT.FILE_NAME%TYPE,
      PI_FILE_SIZE IN CMS_ATTACHMENT.FILE_SIZE%TYPE,
      PI_FILE_CONTENT_TYPE IN CMS_ATTACHMENT.FILE_CONTENT_TYPE%TYPE,
      PI_FILEDATA IN CMS_ATTACHMENT.FILE_DATA%TYPE,
      PI_UPLOADED_BY IN CMS_ATTACHMENT.UPLOADED_BY%TYPE,
      PO_ATTACHMENT_ID OUT NUMBER
  ) AS
  L_ATTACHMENT_ID NUMBER;
  BEGIN
      INSERT INTO CMS_ATTACHMENT(DELIVERABLE_ID,FILE_NAME,FILE_SIZE,FILE_CONTENT_TYPE,FILE_DATA,UPLOADED_BY,UPLOADED_ON)
        VALUES (PI_DELIVERABLE_ID,PI_FILE_NAME,PI_FILE_SIZE,PI_FILE_CONTENT_TYPE,PI_FILEDATA,PI_UPLOADED_BY,SYSDATE)
        RETURNING ATTACHMENT_ID INTO L_ATTACHMENT_ID;
        PO_ATTACHMENT_ID := L_ATTACHMENT_ID;
  END PROC_INS_FILEDATA;

  PROCEDURE PROC_DEL_FILEDATA
  (
    PI_ATTACHMENT_ID IN CMS_ATTACHMENT.ATTACHMENT_ID%TYPE,
    PI_CHANGED_BY IN CMS_ATTACHMENT.CHANGED_BY%TYPE,
    PO_RETURN_CODE OUT NUMBER
  ) AS
  BEGIN
    UPDATE CMS_ATTACHMENT SET
      IS_ACTIVE = 'N',
      CHANGED_BY = PI_CHANGED_BY,
      CHANGED_ON = SYSDATE
      WHERE ATTACHMENT_ID = PI_ATTACHMENT_ID;
      PO_RETURN_CODE := 0;

  EXCEPTION
      WHEN OTHERS THEN
        PO_RETURN_CODE := SQLCODE;
  END PROC_DEL_FILEDATA;

END CMS_FILE_UPLOAD_PKG;

/
