--------------------------------------------------------
--  DDL for View VW_CMS_DELIVERABLE_DETAILS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "APPS_ADMIN"."VW_CMS_DELIVERABLE_DETAILS" ("DELIVERABLE_ID", "SEQUENCE_NO", "COMPOSITE_KEY", "TYPE_ID", "DUE_DATE", "DIRECTORATE_ID", "DEPARTMENT_ID", "STATUS_ID", "DATE_SUBMITTED", "DATE_APPROVED", "CREATED_BY", "CREATED_ON", "IS_ACTIVE", "REQUIREMENT_ID", "UPLOAD_FILE_REQUIRED", "DESCRIPTION", "IS_INFORMATION_ONLY", "NOTIFY_MANAGER", "REASON_FOR_REJECTION", "DAYS", "TYPENAME", "STATUS_DESC", "CREATEDBY", "DIRECTORATE", "DEPTNAME", "REQUIREMENT", "FREQUENCY_ID", "OWNER", "OWNERID", "CLAUSENUM", "FREQNAME", "FYDUE", "QUARTER") AS 
  SELECT DELI."DELIVERABLE_ID",
    DELI."SEQUENCE_NO",
    DELI."COMPOSITE_KEY",
    DELI."TYPE_ID",
    DELI."DUE_DATE",
    DELI."DIRECTORATE_ID",
    DELI."DEPARTMENT_ID",
    DELI."STATUS_ID",
    DELI."DATE_SUBMITTED",
    DELI."DATE_APPROVED",
    DELI."CREATED_BY",
    DELI."CREATED_ON",
    DELI."IS_ACTIVE",
    DELI."REQUIREMENT_ID",
    DELI."UPLOAD_FILE_REQUIRED",
    DELI."DESCRIPTION",
    DELI."IS_INFORMATION_ONLY",
    DELI."NOTIFY_MANAGER",
    DELI."REASON_FOR_REJECTION",
    TRUNC(DELI.DUE_DATE) - TRUNC(SYSDATE) AS DAYS,
    CTT.CONTRACT_NAME                     AS TYPENAME,
    STAT.STATUS_DESC,
    PC.EMPLOYEE_NAME AS CREATEDBY,
    ORG.DESCRIPTION  AS DIRECTORATE,
    ORG1.DESCRIPTION AS DEPTNAME,
    REQ.REQUIREMENT,
    DELI.FREQUENCY_ID,
    PC1.EMPLOYEE_NAME AS OWNER,
    MP.SLAC_ID        AS OWNERID,
    CL.CLAUSE_NUMBER || ', ' || CL.CLAUSE_NAME AS CLAUSENUM,
     (SELECT LOOKUP_DESC
    FROM CMS_LOOKUP
    WHERE DELI.FREQUENCY_ID = CMS_LOOKUP.LOOKUP_ID
    AND LOOKUP_GROUP        ='Frequency'
    AND IS_ACTIVE           ='Y'
    ) AS FREQNAME,
    (
    CASE
      WHEN (TO_NUMBER(TO_CHAR(DELI.DUE_dATE,'MM')) > 9)
      THEN 'FY'
        || TO_CHAR(TO_NUMBER(SUBSTR(EXTRACT(YEAR FROM TO_DATE(DELI.DUE_DATE)),3,2)) + 1)
      ELSE 'FY'
        || SUBSTR(EXTRACT(YEAR FROM TO_DATE(DELI.DUE_DATE)),3,2)
    END)                                                                AS FYDUE,
    DECODE(TO_CHAR(DELI.DUE_DATE, 'Q'),'1','2','2','3','3','4','4','1') AS QUARTER
  FROM CMS_DELIVERABLE DELI,
    CMS_CONTRACT_OTHERTYPES CTT,
    CMS_STATUS STAT,
    DW_PEOPLE PC,
    SID.ORGANIZATIONS ORG,
    SID.ORGANIZATIONS ORG1,
   CMS_REQUIREMENT REQ,
    CMS_SOWN_DELI_MAP MP,
    DW_PEOPLE PC1,
    CMS_CLAUSE CL
  WHERE DELI.TYPE_ID      = CTT.CONTRACT_ID (+)
  AND DELI.STATUS_ID      = STAT.STATUS_ID(+)
  AND DELI.CREATED_BY     = PC.EMPLOYEE_ID (+)
  AND ORG.ORG_ID (+)      = TO_CHAR(DELI.DIRECTORATE_ID)
  AND ORG1.ORG_ID (+)     = TO_CHAR(DELI.DEPARTMENT_ID)
  AND DELI.REQUIREMENT_ID = REQ.REQUIREMENT_ID (+)
  AND DELI.DELIVERABLE_ID = MP.DELIVERABLE_ID (+)
  AND MP.SLAC_ID          = PC1.EMPLOYEE_ID (+)
  AND MP.IS_ACTIVE        ='Y'
  AND MP.ISOWNER          = 'Y'
  AND DELI.IS_ACTIVE      ='Y'  
  AND REQ.CLAUSE_ID = CL.CLAUSE_ID (+)
  AND REQ.IS_ACTIVE = 'Y'
;
