--------------------------------------------------------
--  DDL for View VW_CMS_MANAGER
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "APPS_ADMIN"."VW_CMS_MANAGER" ("MANAGER_ID", "DIRECTORATE_CODE", "MANAGER_TYPE", "SLAC_ID", "IS_ACTIVE", "CREATED_BY", "CREATED_ON", "MODIFIED_BY", "MODIFIED_DATE", "ORG_ID", "DESCRIPTION", "EMPLOYEE_NAME") AS 
  SELECT MGR."MANAGER_ID",MGR."DIRECTORATE_CODE",MGR."MANAGER_TYPE",MGR."SLAC_ID",MGR."IS_ACTIVE",MGR."CREATED_BY",MGR."CREATED_ON",MGR."MODIFIED_BY",MGR."MODIFIED_DATE",MGR."ORG_ID", ORG.DESCRIPTION, PC.EMPLOYEE_NAME
    FROM CMS_MANAGER MGR LEFT JOIN SID.ORGANIZATIONS ORG ON MGR.ORG_ID = ORG.ORG_ID LEFT JOIN DW_PEOPLE PC ON PC.EMPLOYEE_ID = MGR.SLAC_ID WHERE MGR.IS_ACTIVE='Y'
;
