--------------------------------------------------------
--  DDL for View VW_CMS_CLAUSE_DETAILS_2
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "APPS_ADMIN"."VW_CMS_CLAUSE_DETAILS_2" ("CLAUSE_ID", "CLAUSE_NAME", "CLAUSE_NUMBER", "SUBCLAUSENAME", "SUBCLAUSENUM", "OWNERNAME", "CONTRACT_NAME", "CLAUSETYPE") AS 
  (SELECT CL.CLAUSE_ID,CL.CLAUSE_NAME,CL.CLAUSE_NUMBER,'' AS SUBCLAUSENAME,'' AS SUBCLAUSENUM, PC.EMPLOYEE_NAME AS OWNERNAME, CONT.CONTRACT_NAME, 'Clause' AS CLAUSETYPE
FROM CMS_CLAUSE CL, DW_PEOPLE PC, CMS_CONTRACT_OTHERTYPES CONT WHERE CONT.CONTRACT_ID = CL.CONTRACT_ID
AND CL.IS_ACTIVE ='Y' AND CL.PARENT_ID IS NULL AND CL.OWNER = PC.EMPLOYEE_ID)
UNION
(SELECT CL."CLAUSE_ID",CL2.CLAUSE_NAME,CL2.CLAUSE_NUMBER,CL."CLAUSE_NAME" as SUBCLAUSENAME,CL."CLAUSE_NUMBER" AS SUBCLAUSENUM,PC.EMPLOYEE_NAME AS OWNERNAME,CONT1.CONTRACT_NAME,
'Subclause' AS CLAUSETYPE
FROM CMS_CLAUSE CL
LEFT JOIN CMS_CONTRACT_OTHERTYPES CONT ON CONT.CONTRACT_ID = CL.CONTRACT_ID LEFT JOIN CMS_CLAUSE CL2 ON CL.PARENT_ID = CL2.CLAUSE_ID LEFT JOIN DW_PEOPLE PC ON CL2.OWNER = PC.EMPLOYEE_ID
LEFT JOIN CMS_CONTRACT_OTHERTYPES CONT1 ON CONT1.CONTRACT_ID = CL2.CONTRACT_ID WHERE CL.IS_ACTIVE='Y' AND CL.PARENT_ID IS NOT NULL
)
;
