--------------------------------------------------------
--  DDL for View VW_CMS_REQUIREMENT_DETAILS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "APPS_ADMIN"."VW_CMS_REQUIREMENT_DETAILS" ("CONTRACT_ID", "CONTRACT_NAME", "PARENT_ID", "GROUP_ID", "CLAUSE_ID", "CLAUSE_NAME", "CLAUSE_NUMBER", "CLAUSE_PARENTID", "OWNER", "REQUIREMENT_ID", "REQUIREMENT", "NOTES", "FREQUENCY_ID", "UPLOAD_FILE_REQUIRED", "START_DATE", "IS_CM_NOTIFIED", "NOTIFIED_DATE", "OWNERNAME", "FREQUENCY", "CLAUSETYPE", "SUBCLAUSENUM", "SUBCLAUSENAME", "CLAUSENUM", "SCFLOWN_PROVISION") AS 
  SELECT CO.CONTRACT_ID,CO.CONTRACT_NAME,CO.PARENT_ID,CO.GROUP_ID, CL.CLAUSE_ID, CL.CLAUSE_NAME,
CL.CLAUSE_NUMBER, CL.PARENT_ID AS CLAUSE_PARENTID,CL.OWNER, REQ.REQUIREMENT_ID,REQ.REQUIREMENT,
REQ.NOTES,REQ.FREQUENCY_ID,REQ.UPLOAD_FILE_REQUIRED,REQ.START_DATE,REQ.IS_CM_NOTIFIED,REQ.NOTIFIED_DATE,PC.EMPLOYEE_NAME  AS OWNERNAME,LUP.LOOKUP_DESC AS FREQUENCY,
'Clause' as CLAUSETYPE,'' as SUBCLAUSENUM, '' AS SUBCLAUSENAME,CL.CLAUSE_NUMBER AS CLAUSENUM,REQ.SCFLOWN_PROVISION
FROM CMS_CONTRACT_OTHERTYPES CO, CMS_CLAUSE CL,CMS_REQUIREMENT REQ,DW_PEOPLE PC,CMS_LOOKUP LUP
WHERE 	REQ.CLAUSE_ID = CL.CLAUSE_ID (+) AND 	CL.CONTRACT_ID = CO.CONTRACT_ID (+) AND OWNER = PC.EMPLOYEE_ID(+) AND CL.PARENT_ID IS NULL
AND LUP.LOOKUP_ID(+) = REQ.FREQUENCY_ID AND REQ.IS_ACTIVE='Y'
UNION
SELECT CO.CONTRACT_ID,CO.CONTRACT_NAME,CO.PARENT_ID,CO.GROUP_ID, CL.CLAUSE_ID, CL2.CLAUSE_NAME,
TRIM(BOTH ' ' FROM CL2.CLAUSE_NUMBER || ' ' || DECODE(CL.CLAUSE_NUMBER,'n/a','',CL.CLAUSE_NUMBER)) AS CLAUSE_NUMBER, CL.PARENT_ID AS CLAUSE_PARENTID,CL2.OWNER, REQ.REQUIREMENT_ID,REQ.REQUIREMENT,
REQ.NOTES,REQ.FREQUENCY_ID,REQ.UPLOAD_FILE_REQUIRED,REQ.START_DATE,REQ.IS_CM_NOTIFIED,REQ.NOTIFIED_DATE,PC.EMPLOYEE_NAME  AS OWNERNAME, LUP.LOOKUP_DESC AS FREQUENCY,'Subclause' AS CLAUSETYPE,
CL.CLAUSE_NUMBER AS SUBCLAUSENUM, CL.CLAUSE_NAME AS SUBCLAUSENAME,CL2.CLAUSE_NUMBER AS CLAUSENUM,REQ.SCFLOWN_PROVISION
FROM CMS_CONTRACT_OTHERTYPES CO, CMS_CLAUSE CL,CMS_REQUIREMENT REQ,DW_PEOPLE PC, CMS_CLAUSE CL2, CMS_LOOKUP LUP
WHERE 	REQ.CLAUSE_ID = CL.CLAUSE_ID (+) AND 	CL2.CONTRACT_ID = CO.CONTRACT_ID (+) AND CL2.OWNER = PC.EMPLOYEE_ID(+) AND CL.PARENT_ID IS NOT NULL
AND CL2.CLAUSE_ID = CL.PARENT_ID AND LUP.LOOKUP_ID(+) = REQ.FREQUENCY_ID AND REQ.IS_ACTIVE ='Y'
;
