--------------------------------------------------------
--  DDL for View VW_CMS_NOTIFY_MAP_DETAILS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "APPS_ADMIN"."VW_CMS_NOTIFY_MAP_DETAILS" ("SCHEDULE_ID", "DELIVERABLE_ID", "LOOKUP_ID", "IS_ACTIVE", "CREATED_BY", "CREATED_ON", "LOOKUP_DESC") AS 
  SELECT NOTIFY."SCHEDULE_ID",NOTIFY."DELIVERABLE_ID",NOTIFY."LOOKUP_ID",NOTIFY."IS_ACTIVE",NOTIFY."CREATED_BY",NOTIFY."CREATED_ON",LKUP.LOOKUP_DESC
    FROM CMS_DELI_NOTIFY_MAP NOTIFY, CMS_LOOKUP LKUP
	WHERE NOTIFY.LOOKUP_ID = LKUP.LOOKUP_ID (+)
	AND NOTIFY.IS_ACTIVE ='Y'
;
