--------------------------------------------------------
--  DDL for View VW_CMS_DELIAPPRVR_MAP_DETAILS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "APPS_ADMIN"."VW_CMS_DELIAPPRVR_MAP_DETAILS" ("DELI_APPR_ID", "DELIVERABLE_ID", "APPROVER_ID", "IS_ACTIVE", "CREATED_BY", "CREATED_ON", "MANAGER_ID", "SLAC_ID", "EMPLOYEE_NAME") AS 
  SELECT DA."DELI_APPR_ID",DA."DELIVERABLE_ID",DA."APPROVER_ID",DA."IS_ACTIVE",DA."CREATED_BY",DA."CREATED_ON", MGR.MANAGER_ID,MGR.SLAC_ID,PC.EMPLOYEE_NAME
    FROM CMS_DELI_APPROVER_MAP DA, CMS_MANAGER MGR, DW_PEOPLE PC
	WHERE
DA.APPROVER_ID = MGR.MANAGER_ID AND
MGR.SLAC_ID = PC.EMPLOYEE_ID AND
DA.IS_ACTIVE ='Y'
;
