--------------------------------------------------------
--  DDL for Table CMS_CONTRACT_FILTER
--------------------------------------------------------

  CREATE TABLE "APPS_ADMIN"."CMS_CONTRACT_FILTER" 
   (	"FILTER_ID" NUMBER, 
	"FILTER_NAME" VARCHAR2(20 BYTE), 
	"IS_ACTIVE" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_ADMIN_DATA" ;
