--------------------------------------------------------
--  DDL for Table CMS_CONTRACT_OTHERTYPES_AUDIT
--------------------------------------------------------

  CREATE TABLE "APPS_ADMIN"."CMS_CONTRACT_OTHERTYPES_AUDIT" 
   (	"CONTRACT_ID" NUMBER, 
	"PARENT_ID" NUMBER, 
	"CONTRACT_NAME" VARCHAR2(50 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_ON" DATE, 
	"CONTRACT_AUDIT_ID" NUMBER, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"GROUP_ID" NUMBER, 
	"SHORT_NAME" VARCHAR2(6 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "APPS_ADMIN_DATA" ;
