--------------------------------------------------------
--  DDL for Table CMS_EMAILSETTINGS
--------------------------------------------------------

  CREATE TABLE "APPS_ADMIN"."CMS_EMAILSETTINGS" 
   (	"SETTINGS_ID" NUMBER, 
	"APP_URL" VARCHAR2(500 BYTE), 
	"SEND_EMAIL" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"IS_ACTIVE" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"OVERRIDE_CURRENT" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"ALTERNATE_EMAIL" VARCHAR2(500 BYTE), 
	"COMPONENT" VARCHAR2(20 BYTE), 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_ON" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_ADMIN_DATA" ;

   COMMENT ON COLUMN "APPS_ADMIN"."CMS_EMAILSETTINGS"."OVERRIDE_CURRENT" IS 'Override the current email settings - if Y can specify the email to use';
