--------------------------------------------------------
--  DDL for Table CMS_DUMMY_LOOKUP
--------------------------------------------------------

  CREATE TABLE "APPS_ADMIN"."CMS_DUMMY_LOOKUP" 
   (	"DUMMY_ID" NUMBER, 
	"DUMMY_DESC" VARCHAR2(20 BYTE), 
	"DUMMY_CODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_ADMIN_DATA" ;
