--------------------------------------------------------
--  DDL for Table CMS_DELIVERABLE
--------------------------------------------------------

  CREATE TABLE "APPS_ADMIN"."CMS_DELIVERABLE" 
   (	"DELIVERABLE_ID" NUMBER, 
	"SEQUENCE_NO" NUMBER, 
	"COMPOSITE_KEY" VARCHAR2(50 BYTE), 
	"TYPE_ID" NUMBER, 
	"DUE_DATE" DATE, 
	"DIRECTORATE_ID" VARCHAR2(20 BYTE), 
	"DEPARTMENT_ID" VARCHAR2(20 BYTE), 
	"STATUS_ID" NUMBER, 
	"DATE_SUBMITTED" DATE, 
	"DATE_APPROVED" DATE, 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_ON" DATE, 
	"IS_ACTIVE" CHAR(1 BYTE) DEFAULT 'Y', 
	"REQUIREMENT_ID" NUMBER, 
	"UPLOAD_FILE_REQUIRED" CHAR(1 BYTE) DEFAULT 'Y', 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"IS_INFORMATION_ONLY" CHAR(1 BYTE) DEFAULT 'N', 
	"NOTIFY_MANAGER" CHAR(1 BYTE) DEFAULT 'Y', 
	"REASON_FOR_REJECTION" VARCHAR2(500 BYTE), 
	"FREQUENCY_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_ADMIN_DATA" ;
