--------------------------------------------------------
--  DDL for Table CMS_DELI_COMMENT
--------------------------------------------------------

  CREATE TABLE "APPS_ADMIN"."CMS_DELI_COMMENT" 
   (	"COMMENT_ID" NUMBER, 
	"DELIVERABLE_ID" NUMBER, 
	"DETAIL" VARCHAR2(4000 BYTE), 
	"IS_ACTIVE" CHAR(1 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_ON" DATE, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "APPS_ADMIN_DATA" ;
