--------------------------------------------------------
--  Constraints for Table CMS_CLAUSE_AUDIT
--------------------------------------------------------

  ALTER TABLE "APPS_ADMIN"."CMS_CLAUSE_AUDIT" MODIFY ("CLAUSE_ID" NOT NULL ENABLE);
  ALTER TABLE "APPS_ADMIN"."CMS_CLAUSE_AUDIT" MODIFY ("CLAUSE_NAME" NOT NULL ENABLE);
  ALTER TABLE "APPS_ADMIN"."CMS_CLAUSE_AUDIT" MODIFY ("CLAUSE_AUDIT_ID" NOT NULL ENABLE);
  ALTER TABLE "APPS_ADMIN"."CMS_CLAUSE_AUDIT" ADD CONSTRAINT "CMS_CLAUSE_AUDIT_PK1" PRIMARY KEY ("CLAUSE_AUDIT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_ADMIN_DATA"  ENABLE;
