--------------------------------------------------------
--  Constraints for Table CMS_DELI_COMMENT
--------------------------------------------------------

  ALTER TABLE "APPS_ADMIN"."CMS_DELI_COMMENT" MODIFY ("COMMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "APPS_ADMIN"."CMS_DELI_COMMENT" MODIFY ("DELIVERABLE_ID" NOT NULL ENABLE);
  ALTER TABLE "APPS_ADMIN"."CMS_DELI_COMMENT" MODIFY ("DETAIL" NOT NULL ENABLE);
  ALTER TABLE "APPS_ADMIN"."CMS_DELI_COMMENT" ADD CONSTRAINT "CMS_DELI_COMMENT_PK" PRIMARY KEY ("COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_ADMIN_DATA"  ENABLE;
  ALTER TABLE "APPS_ADMIN"."CMS_DELI_COMMENT" ADD CONSTRAINT "CMS_DELI_COMMENT_CK1" CHECK (IS_ACTIVE in ('Y','N')) ENABLE;
