--------------------------------------------------------
--  Constraints for Table CMS_DELIVERABLE
--------------------------------------------------------

  ALTER TABLE "APPS_ADMIN"."CMS_DELIVERABLE" MODIFY ("DELIVERABLE_ID" NOT NULL ENABLE);
  ALTER TABLE "APPS_ADMIN"."CMS_DELIVERABLE" ADD CONSTRAINT "CMS_DELIVERABLE_PK" PRIMARY KEY ("DELIVERABLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_ADMIN_DATA"  ENABLE;
  ALTER TABLE "APPS_ADMIN"."CMS_DELIVERABLE" ADD CONSTRAINT "CMS_DELIVERABLE_CHK2" CHECK (IS_INFORMATION_ONLY IN ('Y', 'N')) ENABLE;
  ALTER TABLE "APPS_ADMIN"."CMS_DELIVERABLE" ADD CONSTRAINT "CMS_DELIVERABLE_CHK1" CHECK (UPLOAD_FILE_REQUIRED IN ('Y', 'N')) ENABLE;
  ALTER TABLE "APPS_ADMIN"."CMS_DELIVERABLE" ADD CONSTRAINT "CMS_DELIVERABLE_CHK5" CHECK (NOTIFY_MANAGER IN ('Y', 'N')) ENABLE;
  ALTER TABLE "APPS_ADMIN"."CMS_DELIVERABLE" ADD CONSTRAINT "CMS_DELIVERABLE_CHK3" CHECK (IS_ACTIVE IN ('Y', 'N', 'D')) ENABLE;
