--------------------------------------------------------
--  Constraints for Table CMS_ATTACHMENT
--------------------------------------------------------

  ALTER TABLE "APPS_ADMIN"."CMS_ATTACHMENT" MODIFY ("ATTACHMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "APPS_ADMIN"."CMS_ATTACHMENT" ADD CONSTRAINT "CMS_ATTACHMENT_PK" PRIMARY KEY ("ATTACHMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_ADMIN_DATA"  ENABLE;
  ALTER TABLE "APPS_ADMIN"."CMS_ATTACHMENT" ADD CONSTRAINT "CMS_ATTACHMENT_CK" CHECK (IS_ACTIVE IN ('Y', 'N', 'D')) ENABLE;
