--------------------------------------------------------
--  Constraints for Table CMS_STATUS
--------------------------------------------------------

  ALTER TABLE "APPS_ADMIN"."CMS_STATUS" ADD CONSTRAINT "CMS_STATUS_PK" PRIMARY KEY ("STATUS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_ADMIN_DATA"  ENABLE;
  ALTER TABLE "APPS_ADMIN"."CMS_STATUS" ADD CONSTRAINT "CMS_STATUS_CHK1" CHECK (IS_ACTIVE IN ('Y', 'N')) ENABLE;
  ALTER TABLE "APPS_ADMIN"."CMS_STATUS" MODIFY ("STATUS_ID" NOT NULL ENABLE);
  ALTER TABLE "APPS_ADMIN"."CMS_STATUS" MODIFY ("STATUS_DESC" NOT NULL ENABLE);
  ALTER TABLE "APPS_ADMIN"."CMS_STATUS" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
