--------------------------------------------------------
--  Constraints for Table CMS_REQUIREMENT
--------------------------------------------------------

  ALTER TABLE "APPS_ADMIN"."CMS_REQUIREMENT" ADD CONSTRAINT "CMS_REQUIREMENT_CHK1" CHECK (IS_ACTIVE IN ('Y', 'N', 'D', 'F')) ENABLE;
  ALTER TABLE "APPS_ADMIN"."CMS_REQUIREMENT" ADD CONSTRAINT "CMS_REQUIREMENT_PK" PRIMARY KEY ("REQUIREMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_ADMIN_DATA"  ENABLE;
  ALTER TABLE "APPS_ADMIN"."CMS_REQUIREMENT" MODIFY ("REQUIREMENT_ID" NOT NULL ENABLE);
