--------------------------------------------------------
--  Constraints for Table CMS_SOWN_DELI_MAP
--------------------------------------------------------

  ALTER TABLE "APPS_ADMIN"."CMS_SOWN_DELI_MAP" MODIFY ("SUBOWNER_ID" NOT NULL ENABLE);
  ALTER TABLE "APPS_ADMIN"."CMS_SOWN_DELI_MAP" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "APPS_ADMIN"."CMS_SOWN_DELI_MAP" MODIFY ("ISOWNER" NOT NULL ENABLE);
  ALTER TABLE "APPS_ADMIN"."CMS_SOWN_DELI_MAP" ADD CONSTRAINT "CMS_SUBOWNER_DELI_MAPPING_PK" PRIMARY KEY ("SUBOWNER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_ADMIN_DATA"  ENABLE;
  ALTER TABLE "APPS_ADMIN"."CMS_SOWN_DELI_MAP" ADD CONSTRAINT "CMS_SOWN_DELI_MAP_CHK1" CHECK (IS_ACTIVE IN ('Y', 'N')) ENABLE;
  ALTER TABLE "APPS_ADMIN"."CMS_SOWN_DELI_MAP" ADD CONSTRAINT "CMS_SOWN_DELI_MAP_CHK2" CHECK (ISOWNER IN ('Y', 'N')) ENABLE;
