--------------------------------------------------------
--  Constraints for Table CMS_EMAIL_TYPE
--------------------------------------------------------

  ALTER TABLE "APPS_ADMIN"."CMS_EMAIL_TYPE" ADD CONSTRAINT "CMS_EMAIL_TYPE_PK" PRIMARY KEY ("EMAIL_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_ADMIN_DATA"  ENABLE;
  ALTER TABLE "APPS_ADMIN"."CMS_EMAIL_TYPE" ADD CONSTRAINT "CMS_EMAIL_TYPE_CK2" CHECK (IS_ACTIVE IN ('Y','N')) ENABLE;
  ALTER TABLE "APPS_ADMIN"."CMS_EMAIL_TYPE" ADD CONSTRAINT "CMS_EMAIL_TYPE_CK1" CHECK (is_html in ('Y','N')) ENABLE;
  ALTER TABLE "APPS_ADMIN"."CMS_EMAIL_TYPE" MODIFY ("EMAIL_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "APPS_ADMIN"."CMS_EMAIL_TYPE" MODIFY ("EMAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "APPS_ADMIN"."CMS_EMAIL_TYPE" MODIFY ("EMAIL_TYPE" NOT NULL ENABLE);
  ALTER TABLE "APPS_ADMIN"."CMS_EMAIL_TYPE" MODIFY ("EMAIL_FROM" NOT NULL ENABLE);
  ALTER TABLE "APPS_ADMIN"."CMS_EMAIL_TYPE" MODIFY ("EMAIL_SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "APPS_ADMIN"."CMS_EMAIL_TYPE" MODIFY ("IS_HTML" NOT NULL ENABLE);
  ALTER TABLE "APPS_ADMIN"."CMS_EMAIL_TYPE" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
