--------------------------------------------------------
--  Constraints for Table CMS_FILE_SO_ACTION
--------------------------------------------------------

  ALTER TABLE "APPS_ADMIN"."CMS_FILE_SO_ACTION" ADD CONSTRAINT "CMS_FILE_SO_ACTION_PK" PRIMARY KEY ("SO_ACTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_ADMIN_DATA"  ENABLE;
  ALTER TABLE "APPS_ADMIN"."CMS_FILE_SO_ACTION" MODIFY ("SO_ACTION_ID" NOT NULL ENABLE);
