--------------------------------------------------------
--  File created - Tuesday-August-20-2019   
--------------------------------------------------------
REM INSERTING into CMS_LOOKUP
SET DEFINE OFF;
Insert into CMS_LOOKUP (LOOKUP_ID,LOOKUP_DESC,LOOKUP_GROUP,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,DISPLAY_ORDER) values (1,'Biennial','Frequency','Y','APPS_ADMIN',to_date('01-MAY-13','DD-MON-RR'),'APPS_ADMIN',to_date('26-AUG-13','DD-MON-RR'),2);
Insert into CMS_LOOKUP (LOOKUP_ID,LOOKUP_DESC,LOOKUP_GROUP,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,DISPLAY_ORDER) values (2,'Annual','Frequency','Y','APPS_ADMIN',to_date('01-MAY-13','DD-MON-RR'),'APPS_ADMIN',to_date('26-AUG-13','DD-MON-RR'),1);
Insert into CMS_LOOKUP (LOOKUP_ID,LOOKUP_DESC,LOOKUP_GROUP,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,DISPLAY_ORDER) values (3,'Semi-Annual','Frequency','Y','APPS_ADMIN',to_date('01-MAY-13','DD-MON-RR'),'APPS_ADMIN',to_date('26-AUG-13','DD-MON-RR'),7);
Insert into CMS_LOOKUP (LOOKUP_ID,LOOKUP_DESC,LOOKUP_GROUP,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,DISPLAY_ORDER) values (4,'Quarterly','Frequency','Y','APPS_ADMIN',to_date('01-MAY-13','DD-MON-RR'),'APPS_ADMIN',to_date('26-AUG-13','DD-MON-RR'),6);
Insert into CMS_LOOKUP (LOOKUP_ID,LOOKUP_DESC,LOOKUP_GROUP,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,DISPLAY_ORDER) values (5,'Monthly','Frequency','Y','APPS_ADMIN',to_date('01-MAY-13','DD-MON-RR'),'APPS_ADMIN',to_date('26-AUG-13','DD-MON-RR'),4);
Insert into CMS_LOOKUP (LOOKUP_ID,LOOKUP_DESC,LOOKUP_GROUP,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,DISPLAY_ORDER) values (6,'Semi-Monthly','Frequency','Y','APPS_ADMIN',to_date('01-MAY-13','DD-MON-RR'),'APPS_ADMIN',to_date('26-AUG-13','DD-MON-RR'),8);
Insert into CMS_LOOKUP (LOOKUP_ID,LOOKUP_DESC,LOOKUP_GROUP,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,DISPLAY_ORDER) values (7,'Once','Frequency','Y','APPS_ADMIN',to_date('01-MAY-13','DD-MON-RR'),'APPS_ADMIN',to_date('26-AUG-13','DD-MON-RR'),5);
Insert into CMS_LOOKUP (LOOKUP_ID,LOOKUP_DESC,LOOKUP_GROUP,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,DISPLAY_ORDER) values (8,'90 day Reminder','Notification','Y','APPS_ADMIN',to_date('01-MAY-13','DD-MON-RR'),null,null,null);
Insert into CMS_LOOKUP (LOOKUP_ID,LOOKUP_DESC,LOOKUP_GROUP,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,DISPLAY_ORDER) values (9,'60 day Reminder','Notification','Y','APPS_ADMIN',to_date('01-MAY-13','DD-MON-RR'),null,null,null);
Insert into CMS_LOOKUP (LOOKUP_ID,LOOKUP_DESC,LOOKUP_GROUP,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,DISPLAY_ORDER) values (10,'30 day Reminder','Notification','Y','APPS_ADMIN',to_date('01-MAY-13','DD-MON-RR'),null,null,null);
Insert into CMS_LOOKUP (LOOKUP_ID,LOOKUP_DESC,LOOKUP_GROUP,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,DISPLAY_ORDER) values (11,'10 day Reminder','Notification','Y','APPS_ADMIN',to_date('01-MAY-13','DD-MON-RR'),null,null,null);
Insert into CMS_LOOKUP (LOOKUP_ID,LOOKUP_DESC,LOOKUP_GROUP,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,DISPLAY_ORDER) values (12,'1 day Reminder','Notification','Y','APPS_ADMIN',to_date('01-MAY-13','DD-MON-RR'),null,null,null);
Insert into CMS_LOOKUP (LOOKUP_ID,LOOKUP_DESC,LOOKUP_GROUP,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,DISPLAY_ORDER) values (15,'None','Frequency','Y','APPS_ADMIN',to_date('26-AUG-13','DD-MON-RR'),'APPS_ADMIN',to_date('26-AUG-13','DD-MON-RR'),10);
Insert into CMS_LOOKUP (LOOKUP_ID,LOOKUP_DESC,LOOKUP_GROUP,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,DISPLAY_ORDER) values (13,'Decennial','Frequency','Y','APPS_ADMIN',to_date('26-AUG-13','DD-MON-RR'),'APPS_ADMIN',to_date('26-AUG-13','DD-MON-RR'),3);
Insert into CMS_LOOKUP (LOOKUP_ID,LOOKUP_DESC,LOOKUP_GROUP,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,DISPLAY_ORDER) values (14,'Triennial','Frequency','Y','APPS_ADMIN',to_date('26-AUG-13','DD-MON-RR'),'APPS_ADMIN',to_date('26-AUG-13','DD-MON-RR'),9);
Insert into CMS_LOOKUP (LOOKUP_ID,LOOKUP_DESC,LOOKUP_GROUP,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,DISPLAY_ORDER) values (16,'Upon occurrence','Frequency','Y','APPS_ADMIN',to_date('13-SEP-16','DD-MON-RR'),null,null,11);
COMMIT;
