--------------------------------------------------------
--  File created - Tuesday-August-20-2019   
--------------------------------------------------------
REM INSERTING into CMS_MANAGER SAMPLE DATASET
SET DEFINE OFF;
Insert into CMS_MANAGER (MANAGER_ID,DIRECTORATE_CODE,MANAGER_TYPE,SLAC_ID,IS_ACTIVE,ORG_ID) values (1,'CMA001','CMA',12345,'Y',null);
Insert into CMS_MANAGER (MANAGER_ID,DIRECTORATE_CODE,MANAGER_TYPE,SLAC_ID,IS_ACTIVE,ORG_ID) values (2,'SSO001','SSO',3443432,'Y',null);
Insert into CMS_MANAGER (MANAGER_ID,DIRECTORATE_CODE,MANAGER_TYPE,SLAC_ID,IS_ACTIVE,ORG_ID) values (3,'SSOS001','SSOSUPER',92531,'N',null);
Insert into CMS_MANAGER (MANAGER_ID,DIRECTORATE_CODE,MANAGER_TYPE,SLAC_ID,IS_ACTIVE,ORG_ID) values (4,'SUP001','ADMIN',312150,'Y',null);
Insert into CMS_MANAGER (MANAGER_ID,DIRECTORATE_CODE,MANAGER_TYPE,SLAC_ID,IS_ACTIVE,ORG_ID) values (5,'10000000','DIRADMIN',434343,'Y','10002');
COMMIT;