--------------------------------------------------------
--  File created - Tuesday-August-20-2019   
--------------------------------------------------------
REM INSERTING into CMS_EMAIL_TYPE
SET DEFINE OFF;
Insert into CMS_EMAIL_TYPE (EMAIL_TYPE_ID,EMAIL_ID,EMAIL_TYPE,EMAIL_FROM,EMAIL_TO,EMAIL_CC,EMAIL_BCC,EMAIL_SUBJECT,EMAIL_BODY,IS_HTML,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,LINK_PAGE) values (21,1,'New Deliverable Added and Owner identified','contract@slac.stanford.edu',null,'contract@slac.stanford.edu',null,'SLACTrak Notification: You are assigned as the Owner of a Deliverable','You have been assigned as the Owner for the Deliverable <COMPOSITEKEY>.  As the Owner, you are required to submit the Deliverable within SLACTrak prior to the due date.  Please click on the following link to view the item and assign Sub Owners, as appropriate.  If you have questions, please contact the Contract Management Office at 4240.','N','Y','APPS_ADMIN',to_date('10-JUL-13','DD-MON-RR'),'APPS_ADMIN',to_date('10-JUL-13','DD-MON-RR'),'https://www-bis2.slac.stanford.edu/ContractManagement/');
Insert into CMS_EMAIL_TYPE (EMAIL_TYPE_ID,EMAIL_ID,EMAIL_TYPE,EMAIL_FROM,EMAIL_TO,EMAIL_CC,EMAIL_BCC,EMAIL_SUBJECT,EMAIL_BODY,IS_HTML,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,LINK_PAGE) values (22,2,'Sub Owner Added','contract@slac.stanford.edu',null,'contract@slac.stanford.edu',null,'SLACTrak Notification: You are assigned as the Sub Owner of a Deliverable ','You have been assigned as the Sub Owner for the Deliverable <COMPOSITEKEY>.  As the Sub Owner, please upload the Deliverable and any related documents (e.g., transmittal correspondence) within SLACTrak so that the Owner can submit it prior to the due date.  Please click on the following link to view the Deliverable details.  If you have questions, please contact the Contract Management Office at 4240.','N','Y','APPS_ADMIN',to_date('10-JUL-13','DD-MON-RR'),'APPS_ADMIN',to_date('08-AUG-13','DD-MON-RR'),'https://www-bis2.slac.stanford.edu/ContractManagement/');
Insert into CMS_EMAIL_TYPE (EMAIL_TYPE_ID,EMAIL_ID,EMAIL_TYPE,EMAIL_FROM,EMAIL_TO,EMAIL_CC,EMAIL_BCC,EMAIL_SUBJECT,EMAIL_BODY,IS_HTML,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,LINK_PAGE) values (23,3,'Owner is Changed','contract@slac.stanford.edu',null,'contract@slac.stanford.edu',null,'SLACTrak Notification: Ownership has changed for a Deliverable','You are receiving this email because the ownership has been changed for the Deliverable listed at the following link.  Please click the link to view the Deliverable details.  New Owners may assign Sub Owners, as appropriate.  If you have questions, please contact the Contract Management Office at 4240.','N','Y','APPS_ADMIN',to_date('10-JUL-13','DD-MON-RR'),'APPS_ADMIN',to_date('10-JUL-13','DD-MON-RR'),'https://www-bis2.slac.stanford.edu/ContractManagement/');
Insert into CMS_EMAIL_TYPE (EMAIL_TYPE_ID,EMAIL_ID,EMAIL_TYPE,EMAIL_FROM,EMAIL_TO,EMAIL_CC,EMAIL_BCC,EMAIL_SUBJECT,EMAIL_BODY,IS_HTML,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,LINK_PAGE) values (24,4,'Deliverable Submitted - Information Only','contract@slac.stanford.edu',null,'contract@slac.stanford.edu',null,'SLACTrak Notification: Deliverable Submitted','You are receiving this email because you have been sent an Informational-Only document in the SLACTrak system.  Please click on the following link to see the relevant information.  There is no further action you need to take regarding this item.','N','Y','APPS_ADMIN',to_date('10-JUL-13','DD-MON-RR'),'APPS_ADMIN',to_date('08-AUG-13','DD-MON-RR'),'https://www-bis2.slac.stanford.edu/ContractManagement/');
Insert into CMS_EMAIL_TYPE (EMAIL_TYPE_ID,EMAIL_ID,EMAIL_TYPE,EMAIL_FROM,EMAIL_TO,EMAIL_CC,EMAIL_BCC,EMAIL_SUBJECT,EMAIL_BODY,IS_HTML,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,LINK_PAGE) values (25,5,'Deliverable Submitted - Approval Required','contract@slac.stanford.edu',null,'contract@slac.stanford.edu',null,'SLACTrak Notification: Action Required','You are receiving this email because there is a Deliverable in SLACTrak which requires your review and approval. Please click on the following link to take the appropriate action.  ','N','Y','APPS_ADMIN',to_date('10-JUL-13','DD-MON-RR'),'APPS_ADMIN',to_date('10-JUL-13','DD-MON-RR'),'https://www-bis2.slac.stanford.edu/ContractManagement/');
Insert into CMS_EMAIL_TYPE (EMAIL_TYPE_ID,EMAIL_ID,EMAIL_TYPE,EMAIL_FROM,EMAIL_TO,EMAIL_CC,EMAIL_BCC,EMAIL_SUBJECT,EMAIL_BODY,IS_HTML,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,LINK_PAGE) values (26,6,'Deliverable Approved','contract@slac.stanford.edu',null,'contract@slac.stanford.edu',null,'SLACTrak Notification: Deliverable Approved','The DOE SSO Approver has approved a Deliverable under your ownership. This item requires no further action.  Please click on the following link to see the relevant information. ','N','Y','APPS_ADMIN',to_date('10-JUL-13','DD-MON-RR'),'APPS_ADMIN',to_date('10-JUL-13','DD-MON-RR'),'https://www-bis2.slac.stanford.edu/ContractManagement/');
Insert into CMS_EMAIL_TYPE (EMAIL_TYPE_ID,EMAIL_ID,EMAIL_TYPE,EMAIL_FROM,EMAIL_TO,EMAIL_CC,EMAIL_BCC,EMAIL_SUBJECT,EMAIL_BODY,IS_HTML,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,LINK_PAGE) values (27,7,'Deliverable Re-opened','contract@slac.stanford.edu',null,'contract@slac.stanford.edu',null,'SLACTrak Notification: Deliverable Reopened and Requires Resubmittal to DOE','The DOE SSO Approver has reopened a Deliverable which you submitted. This action does not affect the original due date of the item.  There is an issue which requires your attention.  Please click on the following link to see SSO''s comments and to resubmit the item.  If you have questions, please contact the Contract Management Office at 4240.','N','Y','APPS_ADMIN',to_date('10-JUL-13','DD-MON-RR'),'APPS_ADMIN',to_date('10-JUL-13','DD-MON-RR'),'https://www-bis2.slac.stanford.edu/ContractManagement/');
Insert into CMS_EMAIL_TYPE (EMAIL_TYPE_ID,EMAIL_ID,EMAIL_TYPE,EMAIL_FROM,EMAIL_TO,EMAIL_CC,EMAIL_BCC,EMAIL_SUBJECT,EMAIL_BODY,IS_HTML,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,LINK_PAGE) values (28,8,'File Attached','contract@slac.stanford.edu','contract@slac.stanford.edu',null,null,'SLACTrak Notification: File Uploaded','An Owner has attached a file to a Deliverable in preparation for submittal. Click on the link to see the relevant information','N','Y','APPS_ADMIN',to_date('10-JUL-13','DD-MON-RR'),'APPS_ADMIN',to_date('08-AUG-13','DD-MON-RR'),'https://www-bis2.slac.stanford.edu/ContractManagement/');
Insert into CMS_EMAIL_TYPE (EMAIL_TYPE_ID,EMAIL_ID,EMAIL_TYPE,EMAIL_FROM,EMAIL_TO,EMAIL_CC,EMAIL_BCC,EMAIL_SUBJECT,EMAIL_BODY,IS_HTML,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,LINK_PAGE) values (29,9,'Deliverable Modified','contract@slac.stanford.edu',null,'contract@slac.stanford.edu',null,'SLACTrak Notification: Deliverable Modified','You are the Owner of a Deliverable <COMPOSITEKEY> which has been modified in SLACTrak.  Please click on the following link to view the details.  If you have questions, please contact the Contract Management Office at 4240.','N','Y','APPS_ADMIN',to_date('10-JUL-13','DD-MON-RR'),'APPS_ADMIN',to_date('08-AUG-13','DD-MON-RR'),'https://www-bis2.slac.stanford.edu/ContractManagement/');
Insert into CMS_EMAIL_TYPE (EMAIL_TYPE_ID,EMAIL_ID,EMAIL_TYPE,EMAIL_FROM,EMAIL_TO,EMAIL_CC,EMAIL_BCC,EMAIL_SUBJECT,EMAIL_BODY,IS_HTML,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,LINK_PAGE) values (30,10,'Deliverable is coming Due (includes all Deliverables including reopened)','contract@slac.stanford.edu',null,'contract@slac.stanford.edu',null,'SLACTrak Notification: Deliverable Due Date Notice','You are receiving this email because you are the Owner or the Subowner of Deliverable(s) coming due.<BR><BR>
Subowners are responsible for uploading final Deliverables for the Owner to review and submit through SLACTrak. Owners are required to ensure that uploads are accurate and to submit Deliverables through SLACTrak prior to their due dates.
<BR><BR>','Y','Y','APPS_ADMIN',to_date('10-JUL-13','DD-MON-RR'),'APPS_ADMIN',to_date('08-AUG-13','DD-MON-RR'),'https://www-bis2.slac.stanford.edu/ContractManagement/');
Insert into CMS_EMAIL_TYPE (EMAIL_TYPE_ID,EMAIL_ID,EMAIL_TYPE,EMAIL_FROM,EMAIL_TO,EMAIL_CC,EMAIL_BCC,EMAIL_SUBJECT,EMAIL_BODY,IS_HTML,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,LINK_PAGE) values (31,11,'1 day due date Notice','contract@slac.stanford.edu',null,'contract@slac.stanford.edu',null,'SLACTrak  Notification: 1 Day Reminder Notice ','The following Deliverable(s) are due tomorrow. Owners are required to submit Deliverables through SLACTrak prior to their due dates.<BR><BR>','Y','Y','APPS_ADMIN',to_date('10-JUL-13','DD-MON-RR'),'APPS_ADMIN',to_date('08-AUG-13','DD-MON-RR'),'https://www-bis2.slac.stanford.edu/ContractManagement/');
Insert into CMS_EMAIL_TYPE (EMAIL_TYPE_ID,EMAIL_ID,EMAIL_TYPE,EMAIL_FROM,EMAIL_TO,EMAIL_CC,EMAIL_BCC,EMAIL_SUBJECT,EMAIL_BODY,IS_HTML,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,LINK_PAGE) values (32,12,'Reminder to Add a Deliverable','contract@slac.stanford.edu','contract@slac.stanford.edu',null,null,'SLACTrak Notification: Add a Deliverable','There is a Deliverable that needs to be entered into SLACTrak based on the start date of the requirement. Click on the following link to enter the Deliverable','Y','Y','APPS_ADMIN',to_date('10-JUL-13','DD-MON-RR'),'APPS_ADMIN',to_date('08-AUG-13','DD-MON-RR'),'https://www-bis2.slac.stanford.edu/ContractManagement/');
Insert into CMS_EMAIL_TYPE (EMAIL_TYPE_ID,EMAIL_ID,EMAIL_TYPE,EMAIL_FROM,EMAIL_TO,EMAIL_CC,EMAIL_BCC,EMAIL_SUBJECT,EMAIL_BODY,IS_HTML,IS_ACTIVE,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_DATE,LINK_PAGE) values (41,13,'File uploaded by a Subowner','contract@slac.stanford.edu',null,'contract@slac.stanford.edu',null,'SLACTrak Notification: File Uploaded by a Subowner','A Deliverable file has been uploaded by a Subowner which requires your review and submittal. Click on the link to see the relevant information.','N','Y','APPS_ADMIN',to_date('26-AUG-14','DD-MON-RR'),null,null,null);
COMMIT;
