--------------------------------------------------------
--  DDL for Function CMS_CLAUSE_DET
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "APPS_ADMIN"."CMS_CLAUSE_DET" 
(P_REQID NUMBER)
RETURN VARCHAR2 IS
L_COUNT NUMBER;
L_CLAUSE_NO VARCHAR2(100);
L_CLAUSE_NAME VARCHAR2(200);

BEGIN
  SELECT COUNT(*) INTO L_COUNT FROM VW_CMS_REQUIREMENT_DETAILS WHERE REQUIREMENT_ID = P_REQID;
  IF (L_COUNT > 0) THEN
    BEGIN
      SELECT CLAUSE_NUMBER,CLAUSE_NAME INTO L_CLAUSE_NO,L_CLAUSE_NAME FROM VW_CMS_REQUIREMENT_DETAILS WHERE REQUIREMENT_ID = P_REQID;
      IF ((L_CLAUSE_NAME IS NOT NULL) OR (L_CLAUSE_NAME <> '')) THEN
        RETURN (L_CLAUSE_NO   || ', ' || L_CLAUSE_NAME);
      ELSE
        RETURN L_CLAUSE_NO;
      END IF;
    END;
  ELSE
    RETURN NULL;
  END IF;
END CMS_CLAUSE_DET;

/
