--------------------------------------------------------
--  DDL for Package CMS_EMAIL_NOTIFICATION_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS_ADMIN"."CMS_EMAIL_NOTIFICATION_PKG" AS

  PROCEDURE CMS_EMAIL_PROC
  (
    PI_OBJECT_ID IN CMS_DELIVERABLE.DELIVERABLE_ID%TYPE,
    PI_EMAIL_ID IN CMS_EMAIL_TYPE.EMAIL_ID%TYPE,
    PI_SO_ID IN VARCHAR2,
    PO_RETURN_CODE OUT NUMBER
  );

  PROCEDURE CMS_EMAIL_SUBOWNERS_PROC
  (
    PI_OBJECT_ID IN CMS_DELIVERABLE.DELIVERABLE_ID%TYPE,
    PI_EMAIL_ID IN CMS_EMAIL_TYPE.EMAIL_ID%TYPE,
    PI_SO_ID IN VARCHAR2,
    PI_COMPOSITE_KEY IN VARCHAR2,
    PI_OWNERID IN VARCHAR2,
    PO_RETURN_CODE OUT NUMBER
  );

  FUNCTION GETEPO(ADDR VARCHAR2) RETURN VARCHAR2;

   PROCEDURE REPLACE_PLACEHOLDERS (
     PI_COMPOSITE_KEY IN VARCHAR2
     );

  PROCEDURE CMS_EMAIL_REMINDERS_PROC;
  PROCEDURE CMS_EMAIL_REMINDER_DELIV_PROC;

END CMS_EMAIL_NOTIFICATION_PKG;

/
