--------------------------------------------------------
--  DDL for Package CMS_DELIVERABLE_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "APPS_ADMIN"."CMS_DELIVERABLE_PKG" AS

  /*
    Name........: CMS_DELIVERABLES_PKG
    Description.:  Contains all Data operations on Deliverable object
    Developed by..: Madhu Swaminathan April, 2013
  */

L_MUT_DELIVERABLE_ID NUMBER;
L_MUT_SEQUENCE_NO NUMBER;
L_MUT_COMPOSITE_KEY VARCHAR2(50);
L_MUT_TYPE_ID NUMBER;
L_MUT_DUE_DATE DATE;
L_MUT_DIRECTORATE_ID VARCHAR2(20);
L_MUT_DEPARTMENT_ID VARCHAR2(20);
L_MUT_STATUS_ID NUMBER;
L_MUT_DATE_SUBMITTED DATE;
L_MUT_DATE_APPROVED DATE;
L_MUT_CREATED_BY VARCHAR2(50);
L_MUT_CREATED_ON DATE;
L_MUT_REQUIREMENT_ID NUMBER;
L_MUT_UPLOAD_FILE_REQUIRED CHAR(1);
L_MUT_MODIFIED_BY VARCHAR2(50);
L_MUT_MODIFIED_DATE DATE;
L_MUT_DESCRIPTION VARCHAR2(4000);
L_MUT_IS_INFORMATION_ONLY CHAR(1);
L_MUT_NOTIFY_MANAGER CHAR(1);
L_Mut_Reason_For_Rejection Varchar2(500);
L_MUT_FREQUENCY_ID NUMBER;

PROCEDURE PROC_INS_DELIVERABLE
(
  PI_REQUIREMENT_ID IN CMS_DELIVERABLE.REQUIREMENT_ID%TYPE,
  PI_TYPE_ID IN CMS_DELIVERABLE.TYPE_ID%TYPE,
  PI_DUE_DATE IN CMS_DELIVERABLE.DUE_DATE%TYPE,
  PI_DIRECTORATE_ID IN CMS_DELIVERABLE.DIRECTORATE_ID%TYPE,
  PI_DEPARTMENT_ID IN CMS_DELIVERABLE.DEPARTMENT_ID%TYPE,
  PI_UPLOAD_FILE_REQUIRED IN CMS_DELIVERABLE.UPLOAD_FILE_REQUIRED%TYPE,
  PI_DESCRIPTION IN CMS_DELIVERABLE.DESCRIPTION%TYPE,
  PI_IS_INFORMATION_ONLY IN CMS_DELIVERABLE.IS_INFORMATION_ONLY%TYPE,
  PI_NOTIFY_MANAGER IN CMS_DELIVERABLE.NOTIFY_MANAGER%TYPE,
  PI_FREQUENCY_ID IN CMS_DELIVERABLE.FREQUENCY_ID%TYPE,
  PI_CREATED_BY IN CMS_DELIVERABLE.CREATED_BY%TYPE,
  PO_DELIVERABLE_ID OUT NUMBER
);

PROCEDURE PROC_UPD_DELIVERABLE
(
  PI_DELIVERABLE_ID IN CMS_DELIVERABLE.DELIVERABLE_ID%TYPE,
  PI_DUE_DATE IN CMS_DELIVERABLE.DUE_DATE%TYPE,
  PI_DIRECTORATE_ID IN CMS_DELIVERABLE.DIRECTORATE_ID%TYPE,
  PI_DEPARTMENT_ID IN CMS_DELIVERABLE.DEPARTMENT_ID%TYPE,
 /* PI_STATUS_ID IN CMS_DELIVERABLE.STATUS_ID%TYPE,*/
  PI_UPLOAD_FILE_REQUIRED IN CMS_DELIVERABLE.UPLOAD_FILE_REQUIRED%TYPE,
  PI_DESCRIPTION IN CMS_DELIVERABLE.DESCRIPTION%TYPE,
  PI_IS_INFORMATION_ONLY IN CMS_DELIVERABLE.IS_INFORMATION_ONLY%TYPE,
  PI_NOTIFY_MANAGER IN CMS_DELIVERABLE.NOTIFY_MANAGER%TYPE,
  PI_FREQUENCY_ID IN CMS_DELIVERABLE.FREQUENCY_ID%TYPE,
  PI_MODIFIED_BY IN CMS_DELIVERABLE.MODIFIED_BY%TYPE,
  PI_SEND_EMAIL IN VARCHAR2,
  PO_RETURN_CODE OUT NUMBER
);

PROCEDURE PROC_DEL_DELIVERABLE
(
  PI_DELIVERABLE_ID IN CMS_DELIVERABLE.DELIVERABLE_ID%TYPE,
  PI_MODIFIED_BY IN CMS_DELIVERABLE.MODIFIED_BY%TYPE,
  PO_RETURN_CODE OUT NUMBER
);

PROCEDURE PROC_UPD_STATUS
(
  PI_DELIVERABLE_ID IN CMS_DELIVERABLE.DELIVERABLE_ID%TYPE,
  PI_STATUS_ID IN CMS_DELIVERABLE.STATUS_ID%TYPE,
  PI_REASON_FOR_REJECTION IN CMS_DELIVERABLE.REASON_FOR_REJECTION%TYPE,
  Pi_Modified_By In Cms_Deliverable.Modified_By%Type,
  PI_SENDEMAIL IN VARCHAR2, 
  PO_RETURN_CODE OUT NUMBER
);

PROCEDURE PROC_INS_SUBOWNERS
(
  PI_DELIVERABLE_ID IN CMS_SOWN_DELI_MAP.DELIVERABLE_ID%TYPE,
  PI_SLAC_ID IN CMS_SOWN_DELI_MAP.SLAC_ID%TYPE,
  PI_ISOWNER IN CMS_SOWN_DELI_MAP.ISOWNER%TYPE,
  PI_CREATED_BY IN CMS_SOWN_DELI_MAP.CREATED_BY%TYPE,
  PO_RETURN_CODE OUT NUMBER
);

PROCEDURE PROC_DEL_SUBOWNERS
(
  PI_DELIVERABLE_ID IN CMS_SOWN_DELI_MAP.DELIVERABLE_ID%TYPE,
  PI_ISOWNER IN CMS_SOWN_DELI_MAP.ISOWNER%TYPE,
  PI_MODIFIED_BY IN CMS_SOWN_DELI_MAP.MODIFIED_BY%TYPE,
  PO_RETURN_CODE OUT NUMBER
);

PROCEDURE PROC_INS_NOTIFICATION_SCHEDULE
(
  PI_DELIVERABLE_ID IN CMS_DELI_NOTIFY_MAP.DELIVERABLE_ID%TYPE,
  PI_LOOKUP_ID IN CMS_DELI_NOTIFY_MAP.LOOKUP_ID%TYPE,
  PI_CREATED_BY IN CMS_DELI_NOTIFY_MAP.CREATED_BY%TYPE,
  PO_RETURN_CODE OUT NUMBER
);

PROCEDURE PROC_DEL_NOTIFICATION_SCHEDULE
(
  PI_DELIVERABLE_ID IN CMS_DELI_NOTIFY_MAP.DELIVERABLE_ID%TYPE,
  PI_MODIFIED_BY IN CMS_DELI_NOTIFY_MAP.MODIFIED_BY%TYPE,
  PO_RETURN_CODE OUT NUMBER
);

PROCEDURE PROC_INS_APPROVER
(
  PI_DELIVERABLE_ID IN CMS_DELI_APPROVER_MAP.DELIVERABLE_ID%TYPE,
  PI_APPROVER_ID IN CMS_DELI_APPROVER_MAP.APPROVER_ID%TYPE,
  PI_CREATED_BY IN CMS_DELI_APPROVER_MAP.CREATED_BY%TYPE,
  PO_RETURN_CODE OUT NUMBER
);

PROCEDURE PROC_DEL_APPROVER
(
  PI_DELIVERABLE_ID IN CMS_DELI_APPROVER_MAP.DELIVERABLE_ID%TYPE,
  PI_MODIFIED_BY IN CMS_DELI_APPROVER_MAP.MODIFIED_BY%TYPE,
  PO_RETURN_CODE OUT NUMBER
);

PROCEDURE PROC_INS_SSOLOG
(
  PI_DESCRIPTION IN CMS_SSO_LOG.DESCRIPTION%TYPE,
  PI_DELIVERABLE_ID IN CMS_SSO_LOG.DELIVERABLE_ID%TYPE,
  PI_SLAC_ID IN CMS_SSO_LOG.SLAC_ID%TYPE,
  PI_CREATED_BY IN CMS_SSO_LOG.CREATED_BY%TYPE,
  PO_RETURN_CODE OUT NUMBER

);

PROCEDURE PROC_INS_SOFILEACTION
(
  PI_DELIVERABLE_ID IN CMS_FILE_SO_ACTION.DELIVERABLE_ID%TYPE,
  PI_ACTION_BY IN CMS_FILE_SO_ACTION.ACTION_BY%TYPE,
  PI_EMAIL_SENT IN CMS_FILE_SO_ACTION.EMAIL_SENT%TYPE,
  PI_DONE_UPLOAD IN CMS_FILE_SO_ACTION.DONE_UPLOAD%TYPE,
  PO_RETURN_CODE OUT NUMBER


);



END CMS_DELIVERABLE_PKG;

/
