--------------------------------------------------------
--  Ref Constraints for Table CMS_DELIVERABLE
--------------------------------------------------------

  ALTER TABLE "APPS_ADMIN"."CMS_DELIVERABLE" ADD CONSTRAINT "CMS_DELIVERABLE_REQ_FK4" FOREIGN KEY ("REQUIREMENT_ID")
	  REFERENCES "APPS_ADMIN"."CMS_REQUIREMENT" ("REQUIREMENT_ID") ENABLE;
  ALTER TABLE "APPS_ADMIN"."CMS_DELIVERABLE" ADD CONSTRAINT "CMS_DELIVERABLE_FREQ_FK5" FOREIGN KEY ("FREQUENCY_ID")
	  REFERENCES "APPS_ADMIN"."CMS_LOOKUP" ("LOOKUP_ID") ENABLE;
  ALTER TABLE "APPS_ADMIN"."CMS_DELIVERABLE" ADD CONSTRAINT "CMS_DELIVERABLE_TYPE_FK2" FOREIGN KEY ("TYPE_ID")
	  REFERENCES "APPS_ADMIN"."CMS_CONTRACT_OTHERTYPES" ("CONTRACT_ID") ENABLE;
  ALTER TABLE "APPS_ADMIN"."CMS_DELIVERABLE" ADD CONSTRAINT "CMS_DELIVERABLE_STATUS_FK3" FOREIGN KEY ("STATUS_ID")
	  REFERENCES "APPS_ADMIN"."CMS_STATUS" ("STATUS_ID") ENABLE;
