--------------------------------------------------------
--  Ref Constraints for Table CMS_REQUIREMENT
--------------------------------------------------------

  ALTER TABLE "APPS_ADMIN"."CMS_REQUIREMENT" ADD CONSTRAINT "CMS_REQUIREMENT_CLAUSE_FK2" FOREIGN KEY ("CLAUSE_ID")
	  REFERENCES "APPS_ADMIN"."CMS_CLAUSE" ("CLAUSE_ID") DISABLE;
  ALTER TABLE "APPS_ADMIN"."CMS_REQUIREMENT" ADD CONSTRAINT "CMS_REQUIREMENT_LOOKUPS_FK1" FOREIGN KEY ("FREQUENCY_ID")
	  REFERENCES "APPS_ADMIN"."CMS_LOOKUP" ("LOOKUP_ID") ENABLE;
