--------------------------------------------------------
--  Ref Constraints for Table CMS_CLAUSE
--------------------------------------------------------

  ALTER TABLE "APPS_ADMIN"."CMS_CLAUSE" ADD CONSTRAINT "CMS_CLAUSE_PARENTID_FK1" FOREIGN KEY ("PARENT_ID")
	  REFERENCES "APPS_ADMIN"."CMS_CLAUSE" ("CLAUSE_ID") ENABLE;
  ALTER TABLE "APPS_ADMIN"."CMS_CLAUSE" ADD CONSTRAINT "CMS_CLAUSE_CONTRCT_FK3" FOREIGN KEY ("CONTRACT_ID")
	  REFERENCES "APPS_ADMIN"."CMS_CONTRACT_OTHERTYPES" ("CONTRACT_ID") ENABLE;
