--------------------------------------------------------
--  Ref Constraints for Table CMS_DELI_APPROVER_MAP
--------------------------------------------------------

  ALTER TABLE "APPS_ADMIN"."CMS_DELI_APPROVER_MAP" ADD CONSTRAINT "CMS_DELI_APPROVER_MAP_APPR_FK2" FOREIGN KEY ("APPROVER_ID")
	  REFERENCES "APPS_ADMIN"."CMS_MANAGER" ("MANAGER_ID") ENABLE;
  ALTER TABLE "APPS_ADMIN"."CMS_DELI_APPROVER_MAP" ADD CONSTRAINT "CMS_DELI_APPROVER_MAP_DEL_FK1" FOREIGN KEY ("DELIVERABLE_ID")
	  REFERENCES "APPS_ADMIN"."CMS_DELIVERABLE" ("DELIVERABLE_ID") ENABLE;
