--------------------------------------------------------
--  DDL for Index CMS_DELIVERABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS_ADMIN"."CMS_DELIVERABLE_PK" ON "APPS_ADMIN"."CMS_DELIVERABLE" ("DELIVERABLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_ADMIN_DATA" ;
