--------------------------------------------------------
--  DDL for Index IDX_FREQID
--------------------------------------------------------

  CREATE INDEX "APPS_ADMIN"."IDX_FREQID" ON "APPS_ADMIN"."CMS_REQUIREMENT" ("FREQUENCY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_ADMIN_DATA" ;
